version: '3.8'

services:
  postgre: 
    image: postgres:13
    container_name: airflow_postgre
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

  airflow-init:
    build: .
    container_name: airflow_init
    entrypoint: airflow db init
    environment: &airflow-env
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgre/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    depends_on:
      - postgre

  webserver:
    build: .
    container_name: airflow_web
    ports:
      - "8088:8080"
    environment: *airflow-env
    command: webserver
    depends_on:
      - airflow-init
    volumes:
      - ./dags:/opt/airflow/dags

  scheduler:
    build: .
    container_name: airflow_scheduler
    command: scheduler
    environment: *airflow-env
    depends_on:
      - webserver
    volumes:
      - ./dags:/opt/airflow/dags

volumes:
  postgres_db: